namespace: dylode
name: vyos_ansible
version: 1.0.0
readme: README.md
authors:
  - dylode
description: contains handy VyOS roles to make your life easier
license: MIT
license_file: 'LICENSE'
tags:
  - vyos
dependencies:
  vyos.vyos: '2.8.0'
repository: https://github.com/dylode/vyos_ansible
issues: https://github.com/dylode/vyos_ansible/issues

