---
- name: Removing source NAT from absent vlans
  vyos.vyos.vyos_config:
    lines:
      - "delete nat source rule {{100+item.vlan_id}}"
  loop: "{{interfaces_vlan.absent}}"
  loop_control:
    label: "{{100+item.vlan_id}}"

- name: Removing source NAT from present vlans
  vyos.vyos.vyos_config:
    lines:
      - "delete nat source rule {{100+item.vlan_id}}"
  loop: "{{interfaces_vlan.present | selectattr('source_nat.state', 'eq', 'absent') }}"
  loop_control:
    label: "{{100+item.vlan_id}}"

