---
- name: Create network groups
  vyos.vyos.vyos_firewall_global:
    config:
      group: "{{firewall.groups}}"

- name: Configure global state policy
  vyos.vyos.vyos_firewall_global:
    config:
      state_policy:
        - connection_type: established
          action: accept
        - connection_type: related
          action: accept
        - connection_type: invalid
          action: drop
